### ISSUE TITLE
queryParams change transitions are awkward to use

### ISSUE THREAD

**Issue by chungwu** [tildeio/router.js#138]
If I call:

```
router.updateURL("/a/b/c")
router.updateURL("/a/b/c?q=yes")
```

And let's say I have a handler for /c.  It looks like that handler's model function will not be called the second time with the new queryParams, and I cannot capture this state change unless I add an event handler for finalyzeQueryParamChange.  Is this the expected / desirable behavior?

**Comment by jmeas** [comment]
Yes, this is desirable and expected. Because one may not always want to fetch new data when the query params change, it's safest to not do it, and provide a hook if the user wants to change that.

In Ember, they obscure the event behind a flag, `refreshModel`, which is configured on a per-param basis.

[Read more here.](http://guides.emberjs.com/v1.13.0/routing/query-params/)
