### ISSUE TITLE
beforeModel only called on nested routes?

### ISSUE THREAD

**Issue by robdodson** [tildeio/router.js#177]
Given the following config:

```
this.router.map(function(match) {
  match('/').to('home');
  match('/users').to('users');
  match('/users/:id').to('user');
});
```

If I navigate to `/users/123` the `beforeModel` method is only called for `user`.

However if I set it up like this:

```
match('/').to('home', function(match) {
  match('/users').to('users', function(match) {
    match('/:id').to('user');
  });
});
```

`beforeModel` is called for `/`, `/users`, and `/:id`

In [the section on nesting](https://github.com/tildeio/router.js#nesting-without-handlers) it shows an example of both styles and mentions:

> Both work identically, so do whichever you prefer.

But that doesn't seem to be the case unless I'm missing something? (which is very possible :)

**Comment by jmeas** [comment]
@robdodson , my understanding is that the docs here are misleading. I dug into this code a few months back and didn't notice anything in the DSL that would parse out the nested structure from the route string that's passed in.

I don't have time tonight to look into it (packing for a flight in a few hours!), but yeah I'd say I'm 85% sure that this is the docs communicating the wrong message. If you dig into the source, you might be able to confirm this. Otherwise, sometime in the next few days I should have time to check it out more.

My understanding is that the nesting with the associated "nested" callbacks only comes when you explicitly use the nested API in your second example.

**Comment by robdodson** [comment]
Thanks @jmeas, that does seem to be the case. I think, after playing around with this for a while longer, I'm starting to understand the real difference between nesting and having completely individualized routes. At first glance they seem similar but they actually produce very different behaviors. I appreciate all the help these last couple of days, have a safe trip! :airplane:

**Comment by jmeas** [comment]
Happy to help! :v:
